version: '2'
 
services:
  mysql:
    image: mysql
    container_name: mysql-spring
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=fugu
    #restart: always
    networks:
      - spring_mysql_network
 
  fugu:
    depends_on:
      - mysql
    image: srivasd/fugu
    container_name: sfugu
    ports:
      - 8443:8443
    links:
      - mysql:mysql
    networks:
      - spring_mysql_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fugu

networks:
  spring_mysql_network:
    driver: bridge
